from crewai import Crew,Process
from .tasks import research_task,write_task
from .agents import news_researcher,news_writer

## Forming the tech focused crew with some enhanced configuration
def run_crew(topic: str):
    crew=Crew(
        agents=[news_researcher,news_writer],
        tasks=[research_task,write_task],
        process=Process.sequential,

    )

    ## starting the task execution process wiht enhanced feedback

    result = crew.kickoff(inputs={'topic': topic})
    try:
        final_output = result.output if hasattr(result, "output") else str(result)
    except Exception:
        final_output = getattr(write_task, "output", None)

    return final_output or "⚠️ No content generated by CrewAI."